### ISSUE TITLE
what is the scale of our color maps?

### ISSUE THREAD

**Issue by JanetMatsen** [CSE512-16S/fp-wesleybeckner-mdmurbach-janetmatsen#4]
is yellow low, blue high?

**Comment by mdmurbach** [comment]
It's using the d3_scale.scaleViridis() and it looks like it goes from low = purple (#440154) to high = yellow (#fde725)

**Comment by JanetMatsen** [comment]
Also, now that we have the numbers appearing, it is easy to figure out that the yellow is high.
